In [105]:
import numpy as np
import Amazon_Movie_Parser as amp
# save numpy array as csv file
from numpy import savetxt
# load numpy array from csv file
from numpy import loadtxt

In [86]:
# Normalization test
tt = np.array([[2, 4, 6], [1, 5, 8], [20, 4, 6]])
#print(tt.mean(axis=1))
#tt_norm=tt/tt.mean(axis=1)
tt_sum = tt.sum(axis=1)
print(tt.sum(axis=1))
print(np.tile(tt_sum, (3, 1)).T)
# divide each element in the row with the sum of the row so the sum will be equal to 1
tt_norm=tt/np.tile(tt_sum, (3, 1)).T
print(tt_norm)

[12 14 30]
[[12 12 12]
 [14 14 14]
 [30 30 30]]
[[0.16666667 0.33333333 0.5       ]
 [0.07142857 0.35714286 0.57142857]
 [0.66666667 0.13333333 0.2       ]]


In [101]:
def Normalize_Array(arr_to_normalize):
    arr_sum_per_row = arr_to_normalize.sum(axis=1)
    arr_norm = arr_to_normalize/np.tile(arr_sum_per_row, (arr_sum_per_row.shape[0], 1)).T
    return arr_norm

In [ ]:
def Normalize_Array1(arr_to_normalize):
    n_rows = arr_to_normalize.shape[0]
    arr_sum_per_row = arr_to_normalize.sum(axis=1)
    arr_norm = arr_to_normalize/np.tile(arr_sum_per_row, (n_rows, 1)).T
    i = 0
    for i in range(n_rows):
        j = 0
        for j in range(n_rows):
            arr_norm[j][i] = arr_norm[i][j]
            j += 1
    i += 1
    
    return arr_norm

In [ ]:
lst_test = [('A141HP4LYPW', 'B003AI2VGA', '3.0'),
 ('B000063W1R', 'A141HP4LYPW', '4.0'),
 ('6304286961', 'A141HP4LYPW', '5.0'),
 ('A141HP4LYPW', '5556167281', '5.0')]
print(lst_test)

lst_ordered = amp.Reorganize_Edges_List(lst_test)
print(lst_ordered)

In [2]:
lst_test = [('A141HP4LYPW', 'B003AI2VGA', '3.0'),
 ('B000063W1R', 'A141HP4LYPW', '4.0'),
 ('6304286961', 'A141HP4LYPW', '5.0'),
 ('A141HP4LYPW', '5556167281', '5.0')]
print(lst_test)

df_movies = amp.Reorganize_Edges_DataFrame(lst_test)
print(df_movies)

[('A141HP4LYPW', 'B003AI2VGA', '3.0'), ('B000063W1R', 'A141HP4LYPW', '4.0'), ('6304286961', 'A141HP4LYPW', '5.0'), ('A141HP4LYPW', '5556167281', '5.0')]
Graph has been reorganized as a DataFrame, row format: ['userId', 'movieId', 'score']
       userId      movieId score
0  B003AI2VGA  A141HP4LYPW   3.0
1  B000063W1R  A141HP4LYPW   4.0
2  6304286961  A141HP4LYPW   5.0
3  5556167281  A141HP4LYPW   5.0


In [81]:
P

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [3., 4., 5., 5., 0.]])

In [25]:
df_movies.loc[(df_movies['userId'] == 'B003AI2VGA') & (df_movies['movieId'] == 'A141HP4LYPW')]

userId      movieId score
0  B003AI2VGA  A141HP4LYPW   3.0

In [68]:
type(df_movies['movieId'].unique())

numpy.ndarray

In [53]:
#edge_index = df_movies.query("movieId == 'A141HP4LYPW' and userId == 'B003AI2VGA'").index
edge_index = df_movies.query("movieId == 'A141HP4LYPW' and userId == 'B003AI2VGAzzzzz'").index
# below returns series (pandas.core.series.Series) because
# type(edge_index) = pandas.core.indexes.numeric.Int64Index
# edge_index = Int64Index([0], dtype='int64')
# we will assume that there will be ONLY 1 MATCH to our query (it must be so)
# that's why, we will pick the 1st index
# len(edge_index) !=0 mean
if len(edge_index) != 0:
    df_movies.iloc[edge_index[0], 2]
else:
    print('no edge found')
#df_movies.loc[edge_index[0], 'score']

no edge found


In [71]:
node_movies = df_movies['movieId'].unique()
node_users = df_movies['userId'].unique()
nodes = np.concatenate((node_users, node_movies), axis=0)
print(nodes)

['B003AI2VGA' 'B000063W1R' '6304286961' '5556167281' 'A141HP4LYPW']


In [82]:
node_movies = df_movies['movieId'].unique()
node_users = df_movies['userId'].unique()
nodes = np.concatenate((node_users, node_movies), axis=0)
n_nodes = len(nodes)
P = np.zeros((n_nodes, n_nodes))

i = 0
for n_r in nodes:
    j = 0
    for n_c in nodes:
        edge_index = df_movies.query("movieId == '" + n_r + "' and userId == '" + n_c + "'").index
        if len(edge_index) != 0:
            P[i][j] = df_movies.iloc[edge_index[0], 2]
            P[j][i] = P[i][j]
        j += 1
    i += 1
        

In [91]:
P_norm = Normalize_Array(P)
print(P_norm)

[[0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         1.        ]
 [0.17647059 0.23529412 0.29411765 0.29411765 0.        ]]


In [111]:
np.round(P_norm, 6)

array([[0.      , 0.      , 0.      , 0.      , 1.      ],
       [0.      , 0.      , 0.      , 0.      , 1.      ],
       [0.      , 0.      , 0.      , 0.      , 1.      ],
       [0.      , 0.      , 0.      , 0.      , 1.      ],
       [0.176471, 0.235294, 0.294118, 0.294118, 0.      ]])

In [106]:
savetxt('data.csv', P, delimiter=',')

In [ ]:
data = loadtxt('data.csv', delimiter=',')

In [ ]:
arr_sum_per_row = arr_to_normalize.sum(axis=1)
arr_norm = arr_to_normalize/np.tile(arr_sum_per_row, (arr_sum_per_row.shape[0], 1)).T