In [17]:
import numpy as np
import Amazon_Movie_Parser as amp
import Graph_Amazon_Movies as gam
# save numpy array as csv file
from numpy import savetxt
# load numpy array from csv file
from numpy import loadtxt
import networkx as nx
import datetime
import Computations as cmp
from networkx.algorithms import bipartite
import random

In [19]:
# Normalization test
tt = np.array([[2, 4, 6], [1, 5, 8], [20, 4, 6]])
#print(tt.mean(axis=1))
#tt_norm=tt/tt.mean(axis=1)
tt_sum = tt.sum(axis=1)
print(tt.sum(axis=1))
print(np.tile(tt_sum, (3, 1)).T)
# divide each element in the row with the sum of the row so the sum will be equal to 1
tt_norm=tt/np.tile(tt_sum, (3, 1)).T
print(tt_norm)


[12 14 30]
[[12 12 12]
 [14 14 14]
 [30 30 30]]
[[0.16666667 0.33333333 0.5       ]
 [0.07142857 0.35714286 0.57142857]
 [0.66666667 0.13333333 0.2       ]]


In [35]:
tt =[2, 4, 6, 8, 9, 11]
# random.choices 
random.sample(tt, k=2)

[2, 6]

In [38]:
R=np.zeros(5)
R[2]=1
print(R)

[0. 0. 1. 0. 0.]


In [ ]:
cmp1 = cmp.GraphComp()
#Normalize_Matrix(self, arr_to_normalize, dim = 'row'):
tt = np.array([[2, 4, 6], [1, 5, 8], [20, 4, 6]])
tt_norm = cmp1.Normalize_Matrix(tt, dim = 'row')
print(tt_norm)

In [ ]:
#row_sums = a.sum(axis=1)
#new_matrix = a / row_sums[:, numpy.newaxis]

tt = np.array([[2, 4, 6], [1, 5, 8], [20, 4, 6]])
tt_row_sums = tt.sum(axis=1)

new_matrix = tt / tt_row_sums[:, np.newaxis]
print(new_matrix)

In [ ]:
def Normalize_Array(arr_to_normalize, axis=0):
    if axis == 1:
        arr_sum_per_row = arr_to_normalize.sum(axis=1)
        arr_norm = arr_to_normalize/np.tile(arr_sum_per_row, (arr_sum_per_row.shape[0], 1)).T
    elif axis == 0:
        arr_sum_per_row = arr_to_normalize.sum(axis=0)
        arr_norm = arr_to_normalize/np.tile(arr_sum_per_row, (arr_sum_per_row.shape[1], 1)).T
    return arr_norm

In [ ]:
lst_test = [('A141HP4LYPW', 'B003AI2VGA', '3.0'),
     ('B000063W1R', 'A141HP4LYPW', '4.0'),
     ('6304286961', 'A141HP4LYPW', '5.0'),
     ('A141HP4LYPW', '5556167281', '5.0')]

# create a sample graph with edges
def create_sample_graph(lst_test):
    '''
    lst_test = [('A141HP4LYPW', 'B003AI2VGA', '3.0'),
     ('B000063W1R', 'A141HP4LYPW', '4.0'),
     ('6304286961', 'A141HP4LYPW', '5.0'),
     ('A141HP4LYPW', '5556167281', '5.0')]
    '''
    print(lst_test)

    df_movies = amp.Reorganize_Edges_DataFrame(lst_test)
    
    return df_movies

In [6]:
grpComp = cmp.GraphComp()

grp = gam.Graph_Amazon()
file_name='data/movies.txt'; n_movies=140; prs_out='dictionary'

max_connected_gr_amazon_movies = grpComp.Create_Bipartite_Giant_Component(grp, file_name, n_movies, prs_out)

P = nx.to_numpy_matrix(max_connected_gr_amazon_movies)
#print(P)

grpComp.Normalize_Matrix(P, dim = 'row')



Calculation time-Crete graph from the movies file: 0:00:00.006679


ValueError: shape too large to be a matrix.

In [15]:
tt_row_sums = P.sum(axis=1)

new_matrix = P / tt_row_sums[np.newaxis][0]
print(new_matrix)

[[0.    1.    0.    ... 0.    0.    0.   ]
 [0.15  0.    0.15  ... 0.    0.    0.   ]
 [0.    0.375 0.    ... 0.    0.    0.   ]
 ...
 [0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]
 [0.    0.    0.    ... 0.    0.    0.   ]]


In [12]:
tt_row_sums[np.newaxis][0].shape

(77, 1)

In [ ]:
lst_test = [('A141HP4LYPW', 'B003AI2VGA', '3.0'),
     ('B000063W1R', 'A141HP4LYPW', '4.0'),
     ('6304286961', 'A141HP4LYPW', '5.0'),
     ('A141HP4LYPW', '5556167281', '5.0')]

grp1 = grp.Graph_Amazon()
grp_test=grp1.Create_Graph_From_List_WITH_Weight(lst_test)

In [ ]:
grp_test.edges.data('weight', default=1)

In [ ]:
grp_test.nodes

In [ ]:
list(grp_test.nodes)[1]

In [ ]:
grp_test.has_edge('A141HP4LYPW', 'B003AI2VGAx')

In [ ]:
gdata=grp_test.get_edge_data('A141HP4LYPW', 'B003AI2VGA')
print(gdata)

In [ ]:
gdata['weight']

In [ ]:
grp_test.get_edge_data('A141HP4LYPW', 'B003AI2VGA')['weight']

In [ ]:
type(grp_test.get_edge_data('A141HP4LYPW', 'B003AI2VGAx'))

In [ ]:
# this gives the first n nodes as movies and the rest as users
# it other words top_nodes (node group with fewer nodes in it) are listed first
P = nx.to_numpy_matrix(grp_test)  ## corresponds to M in the notes
P_norm = Normalize_Array(P)

n_nodes = P.shape[0]   ## P = nxn matrix
R = np.diag(np.ones(n_nodes))
R_zero = R.copy()
beta = 0.15
print(P_norm)
print(R)
print(R_zero)

In [ ]:
# by doing the below conversion, we are just considering the links between the nodes, we ignore the weights
# we try to understand if considering the weights will benefit us or not
P[P>0]=1

In [ ]:
Normalize_Array(P)

In [ ]:
R_P = R.copy()
R_R = R.copy()

In [ ]:
R_P = (1-beta)*np.dot(P_norm, R_P) + beta*R_zero
print(R_P)

# since there is no direction, using P or R as 
R_R = (1-beta)*np.dot(R_R, P_norm) + beta*R_zero
print(R_R)

In [ ]:
R_R[0]

In [ ]:
llt=np.array(list(R_R[3]))

In [ ]:
np.argsort(llt)[0][0][0]

In [ ]:
sorted_nodes=np.argsort(llt)

user_similarity = []

# we will not consider the user himself or movies as similar nodes
for idx in sorted_nodes[0][0]:
    if idx != 3 and idx > 0:
        user_similarity.append(idx)
        
user_similarity_top2 = user_similarity[-2:]

print(user_similarity)
print(user_similarity_top2)
print(list(grp_test.nodes)[user_similarity_top2[0]])

In [ ]:
def Create_Bipartite_Giant_Component_VAL(grp, file_name='data/movies.txt', start_index=40000, n_movies=5000, prs_out='dictionary'):
    start_time = datetime.datetime.now()
    # we can save train and validation data in files so that we don't need to read movies.txt each time

    #max_connected_gr_amazon_movies = grp.Create_Bipartite_VALIDATION(file_name, n_movies, prs_out, start_index)
    max_connected_gr_amazon_movies = grp.Create_Bipartite_VALIDATION(file_name, start_index, n_movies, prs_out)

    #bottom_nodes, top_nodes = bipartite.sets(max_connected_gr_amazon_movies)
    end_time = datetime.datetime.now()
    print('Calculation time-Crete graph from the movies file: {}'.format(end_time-start_time))
    
    return max_connected_gr_amazon_movies

In [ ]:
grp_v = gam.Graph_Amazon()
file_name_v='data/movies.txt'; start_index_v=40000; n_movies_v=5000; prs_out_v='dictionary'

max_connected_gr_amazon_movies_VAL = \
Create_Bipartite_Giant_Component_VAL(grp_v, file_name_v, start_index_v, n_movies_v, prs_out_v)

In [ ]:
max_connected_gr_amazon_movies_VAL.edges

In [ ]:

file_name = 'data/movies.txt'; start_index = 4; n_movies = 5; prs_out = 'screen'

movie_dict_old = amp.AmazonMovies(n_movies, file_name, prs_out)

In [ ]:

file_name = 'data/movies.txt'; start_index = 200; n_movies = 100; prs_out = 'screen'

movie_dict = amp.AmazonMovies_VALIDATION(n_movies, file_name, prs_out, start_index)

In [ ]:
x='abcdaaaaaaaaaaaaaaa'
if 'abcz' in x:
    print(x)

In [ ]:
import Amazon_Movie_Parser as amp
file_name = 'data/movies.txt'; n_movies=50000; prs_out = 'screen'
userID = 'ADFH2AD4HML73';   movieID = 'B00005952Q'
amp.Filter_AmazonMovies(n_movies, userID, movieID, file_name, prs_out)